// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uujdekzsunzvkramesvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1amRla3pzdW56dmtyYW1lc3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTgwOTMsImV4cCI6MjA2NDYzNDA5M30.dk6ZYUtIk3cmyTrvoEB-ww1jgTvya0U8W2BOhAN2gTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);