
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getDatabaseConfig } from '@/config/database';

const config = getDatabaseConfig();

// Cliente principal que se adapta según la configuración
let supabaseClient: any;

if (config.type === 'supabase' && config.supabase) {
  supabaseClient = createClient<Database>(config.supabase.url, config.supabase.anonKey);
} else {
  // Para PostgreSQL local, usar el cliente personalizado
  const { database } = await import('@/integrations/database/client');
  supabaseClient = database.client;
}

export const supabase = supabaseClient;
